# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-24 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201022_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count_c',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 10, 24, 14, 24, 23, 185529), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 10, 24, 14, 24, 23, 186529), verbose_name='Дата'),
        ),
    ]
