# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-25 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20201025_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 10, 25, 16, 17, 29, 771844), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 10, 25, 16, 17, 29, 772803), verbose_name='Дата'),
        ),
    ]
