# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20201103_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
                ('image2', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
                ('image3', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
                ('image4', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
                ('image5', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
                ('image6', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
                ('image7', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
                ('image8', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
                ('image9', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
                ('image10', models.ImageField(default=False, upload_to='', verbose_name='Лого бенда')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 4, 17, 17, 58, 539142), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 4, 17, 17, 58, 540139), verbose_name='Дата'),
        ),
    ]
