# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20201104_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 4, 17, 23, 35, 343328), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image1',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image10',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image2',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image3',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image4',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image5',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image6',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image7',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image8',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image9',
            field=models.ImageField(default=False, upload_to=None, verbose_name='Лого бенда'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 4, 17, 23, 35, 344327), verbose_name='Дата'),
        ),
    ]
