# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-06 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20201206_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 6, 16, 15, 17, 110251), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 6, 16, 15, 17, 111252), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 6, 16, 15, 17, 111252), verbose_name='Дата'),
        ),
    ]
