# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_processor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.AddField(
            model_name='product',
            name='cpu_frequency',
            field=models.CharField(default='0', max_length=5, verbose_name='Частота процессора'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_type',
            field=models.CharField(default='0', max_length=10, verbose_name='Тип экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(default='0', max_length=20, verbose_name='Разрешение экрана'),
        ),
    ]
