# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201019_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='system',
            field=models.CharField(default='system', max_length=100, verbose_name='Операционная система'),
        ),
    ]
