# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cores',
            field=models.CharField(default='0', max_length=5, verbose_name='Кол-во ядер'),
        ),
        migrations.AddField(
            model_name='product',
            name='duo_sim',
            field=models.BooleanField(default=True, verbose_name='Поддержка двух сим карт'),
        ),
    ]
