# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201019_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default=0, max_length=255, verbose_name='Страна производителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default=1, max_length=255, verbose_name='Гарантия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='accum_volume',
            field=models.CharField(max_length=255, verbose_name='Объем батареи мА*ч '),
        ),
    ]
