# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201019_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='case_type',
            field=models.CharField(default='input', max_length=255, verbose_name='Тип корпуса'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_cam_mp',
            field=models.CharField(max_length=255, verbose_name='Основная камера'),
        ),
    ]
