# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201020_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gpu',
            field=models.CharField(default='input', max_length=255, verbose_name='Графический ускроритель'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(default='input', max_length=255, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_inside',
            field=models.CharField(default='input', max_length=255, verbose_name='Объем встроенной памяти'),
        ),
        migrations.AddField(
            model_name='product',
            name='sim_type',
            field=models.CharField(default='input', max_length=255, verbose_name='Тип SIM-карты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=255, verbose_name='Объем оперативной памяти'),
        ),
    ]
