# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201020_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cpu_frequency',
            field=models.CharField(max_length=5, verbose_name='Частота процессора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram_inside',
            field=models.CharField(max_length=255, verbose_name='Объем встроенной памяти'),
        ),
    ]
