# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201020_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash',
            field=models.BooleanField(default=True, verbose_name='Вспышка'),
        ),
        migrations.AddField(
            model_name='product',
            name='mp3_pleer',
            field=models.BooleanField(default=True, verbose_name='MP3 плеер'),
        ),
        migrations.AddField(
            model_name='product',
            name='recorder',
            field=models.BooleanField(default=True, verbose_name='Диктофон'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=0, max_length=255, verbose_name='Размеры (ШхВхТ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='usb_interface',
            field=models.CharField(default=0, max_length=255, verbose_name='Интерфейс USB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weigth',
            field=models.CharField(default=0, max_length=10, verbose_name='Вес г.'),
            preserve_default=False,
        ),
    ]
