# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201103_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='case_type',
            field=models.CharField(default=False, max_length=255, verbose_name='Тип корпуса'),
        ),
    ]
