# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-30 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20201119_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Картинка_1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Картинка_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Картинка_3'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 30, 18, 18, 26, 641618), verbose_name='Дата'),
        ),
    ]
