# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-03 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20201201_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_type',
            field=models.CharField(default=False, max_length=250, verbose_name='Тип экрана'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(default=False, max_length=255, verbose_name='Разрешение экрана'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 3, 12, 25, 10, 595181), verbose_name='Дата'),
        ),
    ]
