# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-06 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20201203_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 6, 16, 8, 15, 723438), verbose_name='Дата'),
        ),
    ]
