# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-06 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 6, 16, 15, 17, 117232), verbose_name='Дата заказа'),
        ),
    ]
